imports:
    - { resource: "Security/services.yml" }
    - { resource: "User/services.yml" }
    - { resource: "Forfait/services.yml" }
    - { resource: "TypePage/services.yml" }

parameters:
    #fos_rest.view_response_listener.class: Senegal\ApiBundle\Listener\ViewResponseListener

services:
    senegal.listener.exception_listener:
        class: Senegal\ApiBundle\Listener\ExceptionListener
        arguments:
            - @service_container
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    senegal_api.param_converter.collection_param_converter:
        class: Senegal\ApiBundle\ParamConverter\CollectionParamConverter
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: request.param_converter, converter: collection_param_converter }