parameters:

    database_driver:     pdo_mysql
    database_host:       "localhost"
    database_port:       "3306"
    database_name:       "senegal"
    database_user:       "root"
    database_password:   "root"