###########
### API ###
###########

api_user:
    resource: "@ApiUserBundle/Resources/config/routing.yml"

senegal_api_authentification:
    resource: "@ApiAuthenticationBundle/Resources/config/routing.yml"

senegal_api_contracts:
    resource: "@ApiContractBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    
    
    
    
#####################
### SENEGAL ADMIN ###
#####################

senegal_admin:
    resource: "@SenegalAdminBundle/Resources/config/routing.yml"

senegal_layout:
    resource: "@SenegalLayoutBundle/Resources/config/routing.yml"

senegal_user:
    resource: "@SenegalUserBundle/Resources/config/routing.yml"

senegal_tools:
    resource: "@SenegalToolsBundle/Resources/config/routing.yml"
