senegal_security:
    resource: "@SenegalSecurityBundle/Resources/config/routing.yml"
    prefix:   /

senegal_front:
    resource: "@SenegalFrontBundle/Controller"
    prefix:   /

senegal_back:
    resource: "@SenegalBackBundle/Controller"
    prefix:   /back

senegal_api:
    resource: "@SenegalApiBundle/Controller"
    prefix:   /api
    defaults: {_format: json}

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc
