api_user:
    resource: "@ApiUserBundle/Resources/config/routing.yml"
    prefix:   /

senegal_api_authentification:
    resource: "@ApiAuthenticationBundle/Resources/config/routing.yml"
    prefix:   /

senegal_api_contracts:
    resource: "@ApiContractBundle/Resources/config/routing.yml"
    prefix:   /
#    
#senegal_api_sdk:
#    resource: "@ApiSdkBundle/Resources/config/routing.yml"
#    prefix:   /

#api_contracts:
#    type: rest
#    resource: "@ApiContractBundle/Resources/config/routing.yml"
#    prefix:   /
#
#api_authentication:
#    resource: "@ApiAuthenticationBundle/Resources/config/routing.yml"
#    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc