senegal_api:
    resource: "@SenegalApiBundle/Controller"
    prefix:   /api
    defaults: {_format: json}

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc
