security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Senegal\SecurityBundle\Entity\User: plaintext

    role_hierarchy:
        ACCOUNT_ADMIN:       USER
        SUPER_ADMIN: [USER, ACCOUNT_ADMIN]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_SUPER_ADMIN' ] }

        api:
           id: senegal.security.user.provider

    firewalls:
        login_firewall:
            pattern:    ^(/back/login|/login)$
            anonymous:  ~
        back_secured_area:
            pattern:    ^/back
            context:     back_authentication
            logout:
                path: /back/logout
                target: /back
            simple-form:
                login_path:  /back/login
                check_path:  /back/login_check
                provider:    api
                authenticator: senegal.security.user.authenticator
                default_target_path: /back
                intention: authenticate
                csrf_provider: security.csrf.token_manager
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login-check
            security: false
            #anonymous: ~

        doc:
            pattern:  ^/api/doc
            security: false

        api:
            pattern: ^/api
            stateless: true
            context:     api_authentication
            simple_preauth:
                authenticator: apikey_authenticator

        # todo: remove this when the security stories are done + add tests (see https://github.com/Behatch/contexts/issues/119)
#        test:
#            pattern:  ^/
#            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/back/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/back, roles: ROLE_ACCOUNT_ADMIN }
        - { path: ^/, roles: ROLE_USER }

