security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ACCOUNT_ADMIN:       USER
        SUPER_ADMIN: [ACCOUNT_ADMIN, USER]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login-check
#            security: false
            anonymous: true

        doc:
            pattern:  ^/api/doc
            security: false

        api:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator

        # todo: remove this when the security stories are done + add tests (see https://github.com/Behatch/contexts/issues/119)
        test:
            pattern:  ^/
            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
