parameters:
    senegal.client.class: GuzzleHttp\Client

services:
    senegal.api.client:
        class: %senegal.client.class%
        arguments:
            - base_url: %api_base_url%

    senegal.app.logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: ['applog', [@monolog.handler.applog]]
        tags:
            - { name: monolog.logger, channel: app }
