contracts:
    type:     rest
    resource: Api\Bundle\ContractBundle\Controller\ContractController

authentification:
    type:     rest
    resource: Api\Bundle\AuthenticationBundle\Controller\AuthController
    
documents:
    type:     rest
    resource: Api\Bundle\ContractBundle\Controller\DocumentController
    
users:
    type:     rest
    resource: Api\Bundle\UserBundle\Controller\UserController