#Revision.orm.yml
Senegal\Api\SdkBundle\Entity\Company:
    type: entity
    table: societes
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
    manyToMany:
        contracts:
            targetEntity: Contract
            mappedBy: distributors
    manyToOne:
        groupesocietes:
            targetEntity: CompanyGroup
            inversedBy: companies
