#Revision.orm.yml
Senegal\Api\SdkBundle\Entity\CompanyGroup:
    type: entity
    table: groupesocietes
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string

    oneToMany:
        companies:
            targetEntity: Company
            mappedBy: group
