Senegal\Api\SdkBundle\Entity\Role:
    type: entity
    table: sf_guard_permission
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: string
    manyToMany:
        users:
            targetEntity: User
            mappedBy: roles
