MigrationVersions:
    type: entity
    table: migration_versions
    id:
        version:
            type: string
            nullable: false
            length: 255
            fixed: false
            id: true
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
