Page:
    type: entity
    manyToOne:
        typePage:
          targetEntity: TypePage
          inversedBy: pages
          joinColumn:
            name: type_page_id
            referencedColumnName: id
    table: page
    uniqueConstraints:
        page_slug_unique:
            columns:
                - slug
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        slug:
            type: string
            nullable: false
            length: 255
            fixed: false
        typePageId:
            type: integer
            nullable: false
            unsigned: false
            column: type_page_id
    lifecycleCallbacks: {  }
