TypeBlock:
    type: entity
    oneToMany:
        features:
          targetEntity: Block
          mappedBy: blocks
    table: type_block
    uniqueConstraints:
        type_block_name_unique:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
