UserHasForfait:
    type: entity
    oneToOne:
      user:
        targetEntity: User
        joinColumn:
          name: user_id
          referencedColumnName: id
      forfait:
        targetEntity: Forfait
        joinColumn:
          name: forfait_id
          referencedColumnName: id
    table: user_has_forfait
    id:
        userId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: user_id
        forfaitId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: forfait_id
    lifecycleCallbacks: {  }
