User:
    type: entity
    table: user
    uniqueConstraints:
        user_login_unique:
            columns:
                - login
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: false
            length: 255
            fixed: false
        password:
            type: string
            nullable: false
            length: 128
            fixed: false
        lastname:
            type: string
            nullable: true
            length: 255
            fixed: false
        firstname:
            type: string
            nullable: true
            length: 255
            fixed: false
        address:
            type: text
            nullable: true
            length: 65535
            fixed: false
        phone:
            type: string
            nullable: true
            length: 64
            fixed: false
        mail:
            type: string
            nullable: true
            length: 512
            fixed: false
        roleId:
            type: integer
            nullable: false
            unsigned: false
            column: role_id
    lifecycleCallbacks: {  }
