#Document.orm.yml
Api\SdkBundle\Entity\Document:
    type: entity
    table: documents
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        reference:
            type:   string
        filePath:
            type:   string
            column: filepath
            unique: true
        description:
            type:   text
        size:
            type:   integer
        releasedAt:
            type:   datetime
            column: date_edition
        createdAt:
            type:   datetime
            column: created_at
        createdBy:
            type:   integer
            column: created_by
        updatedAt:
            type:   datetime
            column: updated_at
        updatedBy:
            type:   integer
            column: updated_by
    manyToOne:
        type:
            targetEntity: DocumentType
            joinColumn:
                name:                 documentsnature_id
                referencedColumnName: id
